ALTER TABLE seniorenclub ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE austrittsgrund ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE interessengruppe ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE funktion ADD COLUMN active TINYINT(1) NOT NULL DEFAULT 1;
